services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_PASSWORD: task_manager
      POSTGRES_USER: task_manager
    ports:
      - 5432:5432