spring:
  application:
    name: Task Manager
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?serverVersion=16&charset=utf8
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: faadd63584c84e672ff5824b4f85226faadd63584c84e672ff5824b4f85226
  accessTokenExpiration: 10m

taskManager:
  api:
    prefix: /api/v1