CREATE TABLE "user"
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    email     VARCHAR(255)                             NOT NULL,
    password  VARCHAR(255)                             NOT NULL,
    user_name VARCHAR(50)                              NOT NULL,
    "role"    VARCHAR(50)                              NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uc_user_email UNIQUE (email),
    CONSTRAINT uc_user_user_name UNIQUE (user_name)
);
