CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    email     VARCHAR(50)                               NOT NULL,
    password  VARCHAR(255)                              NOT NULL,
    user_name VARCHAR(50)                               NOT NULL,
    "role"    VARCHAR(50)                               NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uc_user_email UNIQUE (email),
    CONSTRAINT uc_user_user_name UNIQUE (user_name)
);

CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description TEXT                                    NOT NULL,
    owner_id    BIGINT                                  NOT NULL,
    assignee_id BIGINT                                  NOT NULL,
    status      VARCHAR(50)                             NOT NULL,
    priority    VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id),
    CONSTRAINT owner_fk FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE restrict,
    CONSTRAINT assignee_fk FOREIGN KEY (assignee_id) REFERENCES users(id) ON DELETE restrict
);